let number = 9;
console.log(number + ' times 1 equals ' + 9*1);
console.log(number + ' times 2 equals ' + 9*2);
console.log(number + ' times 3 equals ' + 9*3);
console.log(number + ' times 4 equals ' + 9*4);
console.log(number + ' times 5 equals ' + 9*5);
console.log(number + ' times 6 equals ' + 9*6);
console.log(number + ' times 7 equals ' + 9*7);
console.log(number + ' times 8 equals ' + 9*8);
console.log(number + ' times 9 equals ' + 9*9);
console.log(number + ' times 10 equals ' + 9*10);
